global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "flicksbox"
    static_configs:
      - targets: ["docker.for.mac.localhost:8000"]

  - job_name: "node"
    static_configs:
      - targets:
          - "node-exporter:9100"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alerts.yml"
